#!/usr/bin/env python
import boto3

import os


from mlrf.project_info import ProjectInfo
from mlrf.arguments import arguments_parse
from mlrf.key_pair_factory import KeyPairFactory
from mlrf.stack_factory import StackFactory
from mlrf.bucket_accessor import BucketAccessor
from mlrf.log import set_verbose, log, log_verbose


def create_key_pair_if_req(project_info):
  factory = KeyPairFactory(project_info)
  if factory.keyExists():
    log_verbose(f'key {project_info.key_pair_name()} already exists in AWS account and will not be created')
  else:
    log_verbose(f'key {project_info.key_pair_name()} does not exist yet')
    factory.create_and_save_key_pair()

def info_text():
  with open('./info.txt') as info_file:
    info = info_file.read()
  return info

def upload_project(project_info):
  bucket_accessor = BucketAccessor(project_info)
  bucket_accessor.upload_project()
  bucket_accessor.upload_instance_code()

if __name__ == '__main__':
  args = arguments_parse(info_text())
  set_verbose(args.verbose)
  log_verbose('verbose logging enabled.')
  log_verbose(f'reading project from "{args.project_file}"')
  project_info = ProjectInfo(args.project_file)
  log_verbose(f'project directory is {project_info.directory()}')

  if args.create_key_pair:
    create_key_pair_if_req(project_info)

  if args.create_stack:
    stack_factory = StackFactory(project_info)
    stack_factory.create_or_update()

  if args.run:
    upload_project(project_info)








